manifest:
  remotes:
    - name: slicemk
      url-base: https://github.com/xudongzheng
  projects:
    - name: zmk
      remote: xudongzheng
      revision: v20251223-min
      import: app/west.yml
  self:
    path: config
