manifest:
  remotes:
    - name: xudongzheng
      url-base: https://github.com/xudongzheng
  projects:
    - name: zmk
      remote: xudongzheng
      revision: v20250120-min
      import: app/west.yml
  self:
    path: config
